### ISSUE TITLE
Use Passport Laravel

### ISSUE THREAD

**Issue by JoaoOliveiracc** [KKSzymanowski/laravel-6-firebird#10]
I'm trying to use Laravel's Passport in my application that communicates with a firebirdbd. The composer require runs successfully, however when I try to perform the authentication table migrations I get the following error:

  SQLSTATE [HY000]: General error: -607 unsuccessful metadata update Table users already exists (SQL: create table "users" ("id" INTEGER not null, "name" VARCHAR (255) not null, "email" VARCHAR (255) not null, "email_verified_at" TIMESTAMP, "password" VARCHAR (255) not null, "remember_token" VARCHAR (100), "created_at" TIMESTAMP, "updated_at" TIMESTAMP

I would like to know if this drive has any limitations in relation to migrations from laravel. I thank the attention!

**Comment by KKSzymanowski** [comment]
I don't think it's about the driver. It clearly says that the table already
exist, or am I reading it wrong?

pt., 4 gru 2020, 18:35 użytkownik João Monteiro <notifications@github.com>
napisał:

**Comment by JoaoOliveiracc** [comment]
You read it correctly, I apologize. Really what the error says is that the migration has already been done. I was checking my firebird bank, but the new table did not list, it seems that it was the ibexpert that was not updating. Once again I apologize and thank you for your attention.
