### ISSUE TITLE
SQLSTATE [IM001]: Driver does not support this function: driver does not support lastInsertId()

### ISSUE THREAD

**Issue by JoaoOliveiracc** [KKSzymanowski/laravel-6-firebird#11]
SQLSTATE [IM001]: Driver does not support this function: driver does not support lastInsertId(). I saw that https://github.com/jacquestvanzuydam/laravel-firebird/issues/25 proposes a solution, but my question is which model should I declare public $incrementing = false; ?
I thank the attention!

**Comment by KKSzymanowski** [comment]
I would probably create a base class for all models using the firebird database. Something like:
```php
abstract class BaseFirebirdModel extends Model {
    public $incrementing = false;
    protected $connection = 'myFirebirdConnection';
}
```

Nevertheless, you can just set it on every model you use for creating rows in the database.

**Comment by JoaoOliveiracc** [comment]
Thanks @KKSzymanowski!
