### ISSUE TITLE
Unable to connect to firebird server

### ISSUE THREAD

**Issue by rodrigo7331** [KKSzymanowski/laravel-6-firebird#12]
laravel gives me "HY000] [335544721] Unable to complete network request to host "192.168.101.212". {"userId":1,"exception":"[object] (PDOException(code: 335544721): SQLSTATE[HY000] [335544721] Unable to complete network request to host \"192.168.101.212\". at /var/www/html/sistema_bomdia/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70) "

laravel 6.0
firebird 2.5.5

`
        'myFirebirdConnection' => [
            'driver'=> 'firebird',
            'host'=> env('DB_FIREBIRD_HOST', '192.168.101.212'),
            'port'=> env('DB_FIREBIRD_PORT', '53052'),
            'database' => env('DB_FIREBIRD_DATABASE', 'C:/test/AC.fdb'),
            'username' => env('DB_FIREBIRD_USERNAME', 'SYSDBA'),
            'password' => env('DB_FIREBIRD_PASSWORD', 'masterkey'),
            'charset' => env('DB_FIREBIRD_CHARSET', 'ISO-8859-1'),
        ],

 `
the port server is 53052 and i can connect to the server from a python script using fdb lib thats why i think theres something wrong here, please help!

**Comment by KKSzymanowski** [comment]
Try to remove the `port` configuration entry and add the port to the `host` configuration, like so:
```php
'myFirebirdConnection' => [
    'driver'=> 'firebird',
    'host'=> env('DB_FIREBIRD_HOST', '192.168.101.212/53052'),
    'database' => env('DB_FIREBIRD_DATABASE', 'C:/test/AC.fdb'),
    'username' => env('DB_FIREBIRD_USERNAME', 'SYSDBA'),
    'password' => env('DB_FIREBIRD_PASSWORD', 'masterkey'),
    'charset' => env('DB_FIREBIRD_CHARSET', 'ISO-8859-1'),
],
```

**Comment by KKSzymanowski** [comment]
@rodrigo7331 Have you resolved your issue?

**Comment by rodrigo7331** [comment]
Yes, your response is exactly what solved the problem, thx anyways :)

**Comment by rodrigo7331** [comment]
solved the problem with 
'myFirebirdConnection' => [
    'driver'=> 'firebird',
    'host'=> env('DB_FIREBIRD_HOST', '192.168.101.212/53052'),
    'database' => env('DB_FIREBIRD_DATABASE', 'C:/test/AC.fdb'),
    'username' => env('DB_FIREBIRD_USERNAME', 'SYSDBA'),
    'password' => env('DB_FIREBIRD_PASSWORD', 'masterkey'),
    'charset' => env('DB_FIREBIRD_CHARSET', 'ISO-8859-1'),
],
