### ISSUE TITLE
PDOException could not find driver

### ISSUE THREAD

**Issue by aleixo2022** [KKSzymanowski/laravel-6-firebird#15]
I'm getting the error with firebird even though pdo_firebird is installed

 DLL that downloaded: php-7.4.0-interbase-1.1.0-beta-win64
server xampp

_Originally posted by @Alexsandro-Ctba in https://github.com/KKSzymanowski/laravel-6-firebird/issues/5#issuecomment-912550394_

**Comment by KKSzymanowski** [comment]
Have you tried what I posted [here](https://github.com/KKSzymanowski/laravel-6-firebird/issues/5#issuecomment-912554566)?

**Comment by aleixo2022** [comment]
it is installed, too update in the php.ini
![image](https://user-images.githubusercontent.com/72424790/132019135-e84f0726-b85c-4ab6-b812-63e5a5d4c7b6.png)



![image](https://user-images.githubusercontent.com/72424790/132018737-492d5698-99de-45de-979e-2fb52f53ed46.png)

**Comment by KKSzymanowski** [comment]
Ok, but does PHP actually see it?
Anyway this kind of error means there's something wrong with the extension configuration, not with this package.
