### ISSUE TITLE
Compatible firebird 3 or 4 ?

### ISSUE THREAD

**Issue by fillipenorton** [KKSzymanowski/laravel-6-firebird#16]
Is this package recommended to be used with Firebird 3 or Firebird 4 ?

thanks!

**Comment by KKSzymanowski** [comment]
I have only used this for an existing read-only database on Firebird 2.5 so my personal testing have been very limited.
If you would test it with never Firebird versions, please let me know, I will add a note about compatibility to the readme.

**Comment by fillipenorton** [comment]
Ok! thanks
