### ISSUE TITLE
Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by faroldesenvolvimento7** [KKSzymanowski/laravel-6-firebird#17]
Hello
i'd like to know if it's possible to use this package with laravel 5.5 + firebird 4.0
Best regards

**Comment by KKSzymanowski** [comment]
I haven't tested it but the package was developed for Laravel 6 and up so I suppose it won't be compatible with Laravel 5.5.

You can try the 5.5-support branch in this package (on which my package was inspired):
https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.5-support
It is no longer maintained but I still use it in older applications.
Not sure about the Firebird 4 compatibility though. I only connect to Firebird 2.5 database.

**Comment by faroldesenvolvimento7** [comment]
Thanks, gonna give it a try
