### ISSUE TITLE
PHP8 / Laravel8 ?

### ISSUE THREAD

**Issue by Digit999** [KKSzymanowski/laravel-6-firebird#18]
Hi, this package is PHP8/Laravel8 ready ?
I would like use this in a the Apache on Ubuntu Server.

**Comment by KKSzymanowski** [comment]
It should work fine. I'm using it in a couple of PHP 8/Laravel 8 applications without any issues.

**Comment by Digit999** [comment]
great news! Thanks so much

**Comment by KKSzymanowski** [comment]
I added the note about compatibility to the top of the Readme so it's clear for the future.
For other packages you can always look in the composer.json to see if they accept Illuminate components with the version you're looking for.

https://github.com/KKSzymanowski/laravel-6-firebird/blob/master/composer.json#L20-L21
```
    "illuminate/support": "^6.0|^7.0|^8.0",
    "illuminate/database": "^6.0|^7.0|^8.0"
```
