### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by ospang** [KKSzymanowski/laravel-6-firebird#19]
Hey @KKSzymanowski, please add Laravel 9 support. Many thanks in advance!

**Comment by KKSzymanowski** [comment]
I published a new version 6.0.6 with Laravel 9 compatibility. Please check if everything works for you as I have limiting testing capabilities currently.

**Comment by ospang** [comment]
Thank you sir for the swift work! Much appreciated.
