### ISSUE TITLE
Insert don't store with preset charset

### ISSUE THREAD

**Issue by LocalHeroPro** [KKSzymanowski/laravel-6-firebird#2]
In `.env` I set 
```php
DB_FIREBIRD_CHARSET=ISO-8859-2
```
but `insert` don't store data with proper charset - local encoding are missing and I get something like `ZbÄ…szyĹ„`.

**Comment by KKSzymanowski** [comment]
I've read from Firebird databases for 5 years and I haven't quite figured out how the encoding works.

Like I said I haven't ever inserted data but when reading from an ISO-8859-2 database I always got weird characters like you mentioned. A workaround which works for me is to set the connection charset to `ISO-8859-2` and after fetching the data convert it to UTF-8 by calling the following:
```php
iconv('Windows-1250', 'UTF-8', $string)
```
Notice, that I'm explicitly treating the string as `Windows-1250`, not `ISO-8859-2`. This is the only way I got it to work. You can try a similar approach to change the data encoding before running inserts.

**Comment by LocalHeroPro** [comment]
Stored all text data on that way:
```php
Model::insert(
    [
        'column_name' => iconv('UTF-8', 'Windows-1250', 'my string with regional chars'),
        // ....
    ]
);
```
Working as expected.

**Comment by KKSzymanowski** [comment]
Great
