### ISSUE TITLE
Interbase database

### ISSUE THREAD

**Issue by rtfmfm** [KKSzymanowski/laravel-6-firebird#22]
Hello,
I just want to ask if it's possible to use this package to connect to an Interbase database.

Thank you in advance!

**Comment by KKSzymanowski** [comment]
I haven't seen your issue before, sorry.
It's probably irrelevant now, so I'm gonna close this but for future reference: I haven't ever used an Interbase database so I cannot tell you. I heard they are somewhat similar so it's worth giving it a try.
