### ISSUE TITLE
PDOException: could not find driver

### ISSUE THREAD

**Issue by LocalHeroPro** [KKSzymanowski/laravel-6-firebird#5]
I trying connect on Centos 7 providing that connection data:
```php
$dsn = firebird:dbname=localhost:/var/www/cpt.local/data/database.fdb;charSet=ISO-8859-2
```
and get:
```php
PDOException: could not find driver in /var/www/cpt.local/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
--
Stack trace:
#0 /var/www/cpt.local/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
#1 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct()
#2 /var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection()
```
Firebird is running on server:
```sh
● firebird-classic@0.service - Firebird Classic server
   Loaded: loaded (/usr/lib/systemd/system/firebird-classic@.service; static; vendor preset: disabled)
   Active: active (running) since Thu 2020-03-05 22:17:31 CET; 7min ago
 Main PID: 12811 (fb_inet_server)
   CGroup: /system.slice/system-firebird\x2dclassic.slice/firebird-classic@0.service
           └─12811 /usr/sbin/fb_inet_server

Mar 05 22:17:31 centos systemd[1]: Started Firebird Classic server.
```
and pdo, firebird (interbase) php extension are installed
```sh
$ php73 -m | grep pdo
pdo_mysql
pdo_pgsql
pdo_sqlite

$ php73 -m | grep inter
interbase
```
On Windows all working as expected, but on Linux not.
Other PDO connections like PostgreSQL and MariaDB working as expected.

**Comment by KKSzymanowski** [comment]
I think you need the `pdo_firebird` extension which isn't installed based on your `php73 -m | grep pdo` command output.

**Comment by LocalHeroPro** [comment]
I needed that package `php73-php-pdo-dblib` (php73-php-pdo-dblib.x86_64 0:7.3.15-1.el7.remi).

**Comment by aleixo2022** [comment]
I'm getting the error with firebird even though pdo_firebird is installed

**Comment by KKSzymanowski** [comment]
Do you see the error in the command line or in the browser?
For CLI check `php -m | grep pdo_firebird`
For the web create a `info.php` containing:
```php
<?php

phpinfo();
```
open it and check if you see the pdo_firebird extension:
![image](https://user-images.githubusercontent.com/13980973/132015413-1c511788-0bec-441d-bd7f-4405ff40f570.png)

Also, you can simply run
```php
new PDO('firebird:127.0.0.1');
```
wherever you get the error. If you get the error
```
file  is not a valid database
```
then PHP sees the Firebird extension and there may be a problem with this package.
On the other hand if you see 
```
could not find driver
```
then there's a problem with your PHP configuration, not with this package.
