### ISSUE TITLE
how to simulate ibase_gen_id

### ISSUE THREAD

**Issue by lucazap** [KKSzymanowski/laravel-6-firebird#9]
Hi,
in my firebird table i have a "manual" generator for ID_INVOICE primary key in INVOICES table .
I can't change this option.

In my old "php raw" script i was able to do:

```
$id_invoice= ibase_gen_id("GEN_INVOICES_ID",1);
$query1= "INSERT INTO INVOICES(ID_INVOICE,..) VALUES ( $id_invoice, ..);
```

... and then 

`$query2= "INSERT INTO INVOICES_SENT(ID_INVOICE,..) VALUES ( $id_invoice, ..);`

how can i do this now?

**Comment by KKSzymanowski** [comment]
Take a look here: https://stackoverflow.com/questions/8895878/php-pdo-firebird-inserting
This looks like the same issue you're having. I have no experience with inserting data to Firebird databases so I cannot recommend any approach.

**Comment by lucazap** [comment]
Thank you!! It works like a charm 👍 

This is the code:
` DB::connection('myFirebirdConnection')->select("SELECT NEXT VALUE FOR GEN_INVOICES_ID FROM RDB\$DATABASE ");
`

**Comment by KKSzymanowski** [comment]
Nice
